export const navigations = [
  {
    id: 1,
    href: "/",
    name: "profil",
    title: "Profil",
  },
  {
    id: 2,
    href: "/kebijakan",
    name: "kebijakan",
    title: "kebijakan",
  },
  {
    id: 3,
    href: "/data-absolute",
    name: "data-absolute",
    title: "Data Absolute",
  },
  {
    id: 4,
    href: "/status-konservasi",
    name: "status-konservasi",
    title: "Status Konservasi",
  },
  {
    id: 5,
    href: "/dokumentasi",
    name: "dokumentasi",
    title: "dokumentasi",
  },
  {
    id: 6,
    href: "/publikasi",
    name: "publikasi",
    title: "Publikasi",
  },
];

const flora = [
  {
    nama_latin: "Alastromita macrocarpa",
    nama_lokal: "alsomitra",
    "2020": "17",
    "2021": "14",
    "2022": "11",
    "2023": "16",
    "2024": "12",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Allamanda cathartica",
    nama_lokal: "alamanda",
    "2020": "16",
    "2021": "233",
    "2022": "26",
    "2023": "14",
    "2024": "121",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Andropogan aciculatus",
    nama_lokal: "rumput jarum",
    "2020": "14",
    "2021": "14",
    "2022": "213",
    "2023": "233",
    "2024": "1312",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Areca catechu",
    nama_lokal: "pinang merah",
    "2020": "233",
    "2021": "111",
    "2022": "17",
    "2023": "14",
    "2024": "1117",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Artocarpus altilis",
    nama_lokal: "sukun",
    "2020": "14",
    "2021": "8",
    "2022": "16",
    "2023": "111",
    "2024": "11",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Artocarpus elasticus",
    nama_lokal: "benda",
    "2020": "111",
    "2021": "377",
    "2022": "14",
    "2023": "8",
    "2024": "26",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Asystasia gangetica",
    nama_lokal: "rumput israel",
    "2020": "8",
    "2021": "4",
    "2022": "233",
    "2023": "377",
    "2024": "213",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Calophyllum inophyllum",
    nama_lokal: "nyamplung",
    "2020": "377",
    "2021": "288",
    "2022": "14",
    "2023": "4",
    "2024": "17",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Carica papaya",
    nama_lokal: "pepaya",
    "2020": "4",
    "2021": "11",
    "2022": "111",
    "2023": "288",
    "2024": "16",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Casuarina equisetifolia",
    nama_lokal: "cemara laut",
    "2020": "288",
    "2021": "4",
    "2022": "8",
    "2023": "11",
    "2024": "14",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cleome rutidosperma",
    nama_lokal: "maman ungu",
    "2020": "11",
    "2021": "141",
    "2022": "377",
    "2023": "4",
    "2024": "233",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cordyline fruticosa",
    nama_lokal: "hanjuang",
    "2020": "4",
    "2021": "131",
    "2022": "4",
    "2023": "141",
    "2024": "14",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cuphea hyssopifolia",
    nama_lokal: "cuphea",
    "2020": "141",
    "2021": "26",
    "2022": "288",
    "2023": "131",
    "2024": "111",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cyathea contaminans",
    nama_lokal: "paku tiang",
    "2020": "131",
    "2021": "213",
    "2022": "11",
    "2023": "26",
    "2024": "8",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cyperus rotundus",
    nama_lokal: "teki",
    "2020": "14",
    "2021": "1112",
    "2022": "1117",
    "2023": "213",
    "2024": "377",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Delonix regia",
    nama_lokal: "flamboyan",
    "2020": "12",
    "2021": "23",
    "2022": "11",
    "2023": "17",
    "2024": "4",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Digitaria longiflora",
    nama_lokal: "rumput cakar ayam",
    "2020": "17",
    "2021": "112",
    "2022": "26",
    "2023": "16",
    "2024": "288",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Dillenia indica",
    nama_lokal: "sempur",
    "2020": "18",
    "2021": "19",
    "2022": "213",
    "2023": "14",
    "2024": "11",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Durio spp.",
    nama_lokal: "durian",
    "2020": "23",
    "2021": "151",
    "2022": "17",
    "2023": "233",
    "2024": "4",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Eleusine indica",
    nama_lokal: "rumput belulang",
    "2020": "117",
    "2021": "162",
    "2022": "16",
    "2023": "14",
    "2024": "141",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Euphorbia hirta",
    nama_lokal: "patikan kebo",
    "2020": "217",
    "2021": "113",
    "2022": "14",
    "2023": "111",
    "2024": "131",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ficus benjamina",
    nama_lokal: "beringin",
    "2020": "127",
    "2021": "111",
    "2022": "233",
    "2023": "8",
    "2024": "14",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ficus nodosa",
    nama_lokal: "roda",
    "2020": "1138",
    "2021": "8",
    "2022": "14",
    "2023": "377",
    "2024": "12",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ficus septica",
    nama_lokal: "awar-awar",
    "2020": "141",
    "2021": "377",
    "2022": "111",
    "2023": "4",
    "2024": "17",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Flocourtia inermis",
    nama_lokal: "tomi-tomi",
    "2020": "112",
    "2021": "4",
    "2022": "8",
    "2023": "288",
    "2024": "18",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Gliricidia sepium",
    nama_lokal: "gamal",
    "2020": "14",
    "2021": "288",
    "2022": "377",
    "2023": "11",
    "2024": "23",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Hedyotis diffusa",
    nama_lokal: "rumput lidah ular",
    "2020": "1112",
    "2021": "11",
    "2022": "4",
    "2023": "4",
    "2024": "52",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Hibiscus rosa-sinensis",
    nama_lokal: "bunga sepatu",
    "2020": "23",
    "2021": "4",
    "2022": "112",
    "2023": "141",
    "2024": "138",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Inocarpus fagifer",
    nama_lokal: "gayam",
    "2020": "112",
    "2021": "141",
    "2022": "19",
    "2023": "131",
    "2024": "11",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ipomoea aquatica",
    nama_lokal: "kangkung",
    "2020": "19",
    "2021": "131",
    "2022": "151",
    "2023": "14",
    "2024": "131",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ixora coccinea",
    nama_lokal: "bunga asoka",
    "2020": "151",
    "2021": "14",
    "2022": "162",
    "2023": "12",
    "2024": "129",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Mangifera indica",
    nama_lokal: "mangga",
    "2020": "151",
    "2021": "14",
    "2022": "113",
    "2023": "17",
    "2024": "112",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Merremia peltata",
    nama_lokal: "mantangan",
    "2020": "162",
    "2021": "12",
    "2022": "114",
    "2023": "14",
    "2024": "16",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Mikania crenata",
    nama_lokal: "sembung rambat",
    "2020": "113",
    "2021": "17",
    "2022": "111",
    "2023": "1112",
    "2024": "24",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Mimosa pudica",
    nama_lokal: "putri malu",
    "2020": "114",
    "2021": "14",
    "2022": "19",
    "2023": "23",
    "2024": "181",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Musa paradisiaca",
    nama_lokal: "pisang",
    "2020": "111",
    "2021": "112",
    "2022": "117",
    "2023": "112",
    "2024": "19",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Myristica fragans",
    nama_lokal: "pala",
    "2020": "19",
    "2021": "23",
    "2022": "217",
    "2023": "19",
    "2024": "19",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Oldenlandia corymbosa",
    nama_lokal: "rumput mutiara",
    "2020": "117",
    "2021": "112",
    "2022": "127",
    "2023": "151",
    "2024": "1132",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Pandanus odorifer",
    nama_lokal: "pandan laut",
    "2020": "4",
    "2021": "19",
    "2022": "1138",
    "2023": "162",
    "2024": "16",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Plumeria acuminata",
    nama_lokal: "kamboja pohon",
    "2020": "288",
    "2021": "151",
    "2022": "141",
    "2023": "113",
    "2024": "111",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Polyalthia longifolia",
    nama_lokal: "glodokan tiang",
    "2020": "11",
    "2021": "162",
    "2022": "112",
    "2023": "114",
    "2024": "19",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Polyscias scutellaria",
    nama_lokal: "daun mangkok",
    "2020": "4",
    "2021": "113",
    "2022": "14",
    "2023": "889",
    "2024": "117",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Pometia pinnata",
    nama_lokal: "matoa",
    "2020": "141",
    "2021": "19",
    "2022": "1112",
    "2023": "1113",
    "2024": "217",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Roystonea regia",
    nama_lokal: "palem putri",
    "2020": "131",
    "2021": "151",
    "2022": "23",
    "2023": "1612",
    "2024": "127",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ruellia tuberosa",
    nama_lokal: "pletekan",
    "2020": "14",
    "2021": "162",
    "2022": "112",
    "2023": "377",
    "2024": "1138",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Samanea saman",
    nama_lokal: "trembesi",
    "2020": "12",
    "2021": "113",
    "2022": "19",
    "2023": "4",
    "2024": "141",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Sansevieria trifasciata",
    nama_lokal: "sansivera",
    "2020": "16",
    "2021": "288",
    "2022": "151",
    "2023": "288",
    "2024": "112",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Shorea spp.",
    nama_lokal: "meranti",
    "2020": "111",
    "2021": "11",
    "2022": "162",
    "2023": "11",
    "2024": "14",
    iucn: "EN",
    cites: "NA",
    p: "Dilindungi",
  },
  {
    nama_latin: "Sida acuta",
    nama_lokal: "galunggang",
    "2020": "19",
    "2021": "114",
    "2022": "113",
    "2023": "4",
    "2024": "1112",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Spathoglothis papuana",
    nama_lokal: "anggrek tanah",
    "2020": "0",
    "2021": "889",
    "2022": "288",
    "2023": "1141",
    "2024": "23",
    iucn: "LC",
    cites: "Appendix II",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Sterculia macrophylla",
    nama_lokal: "kelumpang",
    "2020": "0",
    "2021": "113",
    "2022": "11",
    "2023": "131",
    "2024": "112",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Syzygium aqueum",
    nama_lokal: "jambu air",
    "2020": "0",
    "2021": "612",
    "2022": "4",
    "2023": "14",
    "2024": "19",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Syzygium oleina",
    nama_lokal: "pucuk merah",
    "2020": "0",
    "2021": "377",
    "2022": "141",
    "2023": "12",
    "2024": "151",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Tabernaemontana divaricata",
    nama_lokal: "kemuning",
    "2020": "0",
    "2021": "0",
    "2022": "131",
    "2023": "17",
    "2024": "162",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Terminalia catappa",
    nama_lokal: "ketapang",
    "2020": "0",
    "2021": "0",
    "2022": "19",
    "2023": "18",
    "2024": "113",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Terminalia mantaly",
    nama_lokal: "ketapang kencana",
    "2020": "0",
    "2021": "0",
    "2022": "151",
    "2023": "23",
    "2024": "114",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Tridax procumbens",
    nama_lokal: "gletang",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "52",
    "2024": "889",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Wodyetia bifurcata",
    nama_lokal: "palem ekor tupai",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "1138",
    "2024": "1113",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Zoysia matrela",
    nama_lokal: "rumput jepang",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "1889",
    "2024": "1612",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Neolamarckia cadamba",
    nama_lokal: "jabon",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "0",
    iucn: "-",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Artocarpus heterophyllus",
    nama_lokal: "nangka",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "5",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Alstonia scholaris",
    nama_lokal: "pulai",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "7",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Pterocarpus indicus",
    nama_lokal: "angsana",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "11",
    iucn: "EN",
    cites: "Appendix II",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ficus hispida",
    nama_lokal: "bisoro",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "8",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Piper aduncum",
    nama_lokal: "sirih hutan",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "171",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Maniltoa grandiflora",
    nama_lokal: "sapu tangan",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "4",
    iucn: "-",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Muntingia calabura",
    nama_lokal: "talok",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "16",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Macaranga hypoleuca",
    nama_lokal: "mahang",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "3",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Christella sp.",
    nama_lokal: "paku",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "243",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Emilia sonchifolia",
    nama_lokal: "tempuh wiyang",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "316",
    iucn: "-",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Hyptis capitata",
    nama_lokal: "rumput knop",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "223",
    iucn: "-",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Chromolaena odorata",
    nama_lokal: "rumput minjangan",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "256",
    iucn: "-",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Stenochlaena palustris",
    nama_lokal: "lemidi",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "344",
    iucn: "-",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Axonopus compressus",
    nama_lokal: "rumput gajah mini",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "655",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Araucaria heterophylla",
    nama_lokal: "cemara norfolk",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "21",
    iucn: "VU",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Spondias dulcis",
    nama_lokal: "kedondong",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "1",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Leucaena leucocephala",
    nama_lokal: "lamtoro",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "37",
    iucn: "CD",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Syzygium malaccense",
    nama_lokal: "jambu dersono",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "1",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Psidium guajava",
    nama_lokal: "jambu biji",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "3",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
];

const fauna = [
  {
    nama_latin: "Actitis hypoleucos",
    nama_lokal: "Trinil Pantai",
    "2020": "3",
    "2021": "8",
    "2022": "2",
    "2023": "3",
    "2024": "4",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Aplonis cantoroides",
    nama_lokal: "Perling Kicau",
    "2020": "5",
    "2021": "2",
    "2022": "12",
    "2023": "11",
    "2024": "3",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ardea intermedia",
    nama_lokal: "Kuntul Perak",
    "2020": "22",
    "2021": "14",
    "2022": "1",
    "2023": "4",
    "2024": "72",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Artamus leucoryn",
    nama_lokal: "Kekep Babi",
    "2020": "2",
    "2021": "31",
    "2022": "32",
    "2023": "22",
    "2024": "16",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Artamus maximus",
    nama_lokal: "Kekep Besar",
    "2020": "3",
    "2021": "2",
    "2022": "2",
    "2023": "31",
    "2024": "11",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Aviceda subcristata",
    nama_lokal: "Baza Pasific",
    "2020": "2",
    "2021": "2",
    "2022": "21",
    "2023": "8",
    "2024": "2",
    iucn: "LC",
    cites: "Appendix II",
    p: "Dilindungi",
  },
  {
    nama_latin: "Bubulcus ibis",
    nama_lokal: "Kuntul Kerbau",
    "2020": "8",
    "2021": "2",
    "2022": "55",
    "2023": "42",
    "2024": "2",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cacatua galerita",
    nama_lokal: "Kakatua Koki",
    "2020": "11",
    "2021": "4",
    "2022": "4",
    "2023": "8",
    "2024": "12",
    iucn: "LC",
    cites: "Appendix II",
    p: "Dilindungi",
  },
  {
    nama_latin: "Caprimulgus macrurus",
    nama_lokal: "Cabak Maling",
    "2020": "5",
    "2021": "8",
    "2022": "4",
    "2023": "16",
    "2024": "4",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Centropus bernsteini",
    nama_lokal: "Bubut Hitam",
    "2020": "7",
    "2021": "42",
    "2022": "22",
    "2023": "10",
    "2024": "3",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ceyx azureus",
    nama_lokal: "Raja Udang Kalung Biru",
    "2020": "3",
    "2021": "8",
    "2022": "31",
    "2023": "3",
    "2024": "11",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cinnyris jugularis",
    nama_lokal: "Burung Madu Sriganti",
    "2020": "11",
    "2021": "16",
    "2022": "8",
    "2023": "5",
    "2024": "4",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Collocalia esculenta",
    nama_lokal: "Walet Sapi",
    "2020": "4",
    "2021": "10",
    "2022": "42",
    "2023": "122",
    "2024": "22",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Columba livia",
    nama_lokal: "Dara Merpati",
    "2020": "22",
    "2021": "3",
    "2022": "8",
    "2023": "2",
    "2024": "31",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Coracina papuensis",
    nama_lokal: "Kepodang Sungu Katula",
    "2020": "31",
    "2021": "5",
    "2022": "16",
    "2023": "34",
    "2024": "8",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Dendrocygna guttata",
    nama_lokal: "Belibis Tutul",
    "2020": "8",
    "2021": "12",
    "2022": "10",
    "2023": "2",
    "2024": "42",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Dicaeum pectorale",
    nama_lokal: "Cabai Papua",
    "2020": "42",
    "2021": "2",
    "2022": "3",
    "2023": "8",
    "2024": "8",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ducula bicolor",
    nama_lokal: "Pergam Laut",
    "2020": "8",
    "2021": "34",
    "2022": "5",
    "2023": "2",
    "2024": "16",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Eclectus roratus",
    nama_lokal: "Nuri Bayan",
    "2020": "16",
    "2021": "2",
    "2022": "22",
    "2023": "14",
    "2024": "10",
    iucn: "LC",
    cites: "Appendix II",
    p: "Dilindungi",
  },
  {
    nama_latin: "Eurystomus orientalis",
    nama_lokal: "Tiong Lampu Biasa",
    "2020": "10",
    "2021": "8",
    "2022": "2",
    "2023": "31",
    "2024": "3",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Gallus gallus domesticus",
    nama_lokal: "Ayam Kampung",
    "2020": "3",
    "2021": "2",
    "2022": "3",
    "2023": "2",
    "2024": "5",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Geoffroyus geoffroyi",
    nama_lokal: "Nuri Pipi Merah",
    "2020": "5",
    "2021": "14",
    "2022": "2",
    "2023": "2",
    "2024": "122",
    iucn: "LC",
    cites: "Appendix II",
    p: "Dilindungi",
  },
  {
    nama_latin: "Gracula religiosa",
    nama_lokal: "Tiong Emas",
    "2020": "14",
    "2021": "22",
    "2022": "42",
    "2023": "8",
    "2024": "12",
    iucn: "LC",
    cites: "Appendix II",
    p: "Dilindungi",
  },
  {
    nama_latin: "Haliaeetus leucogaster",
    nama_lokal: "Elang Laut",
    "2020": "5",
    "2021": "7",
    "2022": "2",
    "2023": "8",
    "2024": "8",
    iucn: "LC",
    cites: "Appendix II",
    p: "Dilindungi",
  },
  {
    nama_latin: "Halcyon cyanoventris",
    nama_lokal: "Cekakak Jawa",
    "2020": "3",
    "2021": "7",
    "2022": "10",
    "2023": "16",
    "2024": "2",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Halcyon chloris",
    nama_lokal: "Cekakak Belukar",
    "2020": "2",
    "2021": "12",
    "2022": "11",
    "2023": "5",
    "2024": "4",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Himantopus himantopus",
    nama_lokal: "Trinil Kaki Merah",
    "2020": "22",
    "2021": "42",
    "2022": "34",
    "2023": "2",
    "2024": "5",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Leucopsar rothschildi",
    nama_lokal: "Jalak Bali",
    "2020": "8",
    "2021": "22",
    "2022": "5",
    "2023": "6",
    "2024": "2",
    iucn: "CR",
    cites: "Appendix I",
    p: "Dilindungi",
  },
  {
    nama_latin: "Lonchura punctulata",
    nama_lokal: "Bondol Peking",
    "2020": "11",
    "2021": "22",
    "2022": "34",
    "2023": "31",
    "2024": "2",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Lonchura spectabilis",
    nama_lokal: "Bondol Papua",
    "2020": "8",
    "2021": "2",
    "2022": "4",
    "2023": "11",
    "2024": "4",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
];

const mangrove = [
  {
    nama_latin: "Acanthus ilicifolius",
    nama_lokal: "Jeruju",
    "2020": "121",
    "2021": "78",
    "2022": "156",
    "2023": "143",
    "2024": "543",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Avicennia alba",
    nama_lokal: "Api-api Hitam",
    "2020": "89",
    "2021": "143",
    "2022": "1828",
    "2023": "876",
    "2024": "654",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Bruiguiera gymnorrizha",
    nama_lokal: "Putut",
    "2020": "678",
    "2021": "876",
    "2022": "121",
    "2023": "156",
    "2024": "1113",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Cocos nucifera",
    nama_lokal: "Kelapa",
    "2020": "78",
    "2021": "156",
    "2022": "3289",
    "2023": "1828",
    "2024": "66",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Dendrocalamus asper",
    nama_lokal: "Bambu",
    "2020": "143",
    "2021": "1828",
    "2022": "678",
    "2023": "121",
    "2024": "78",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Hibiscus tiliaceus",
    nama_lokal: "Waru",
    "2020": "66",
    "2021": "1828",
    "2022": "56",
    "2023": "3289",
    "2024": "143",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Nypa fruticans",
    nama_lokal: "Nipah",
    "2020": "78",
    "2021": "321",
    "2022": "319",
    "2023": "678",
    "2024": "876",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Pandanus sp.",
    nama_lokal: "Pandan",
    "2020": "143",
    "2021": "389",
    "2022": "828",
    "2023": "78",
    "2024": "156",
    iucn: "NE",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Rhizopora mangle",
    nama_lokal: "Mangrove Merah",
    "2020": "876",
    "2021": "678",
    "2022": "121",
    "2023": "143",
    "2024": "1828",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Rhizopora mucronate",
    nama_lokal: "Bakau Laki",
    "2020": "156",
    "2021": "56",
    "2022": "289",
    "2023": "876",
    "2024": "4121",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Rhizopora stylosa",
    nama_lokal: "Bakau Urap",
    "2020": "211",
    "2021": "319",
    "2022": "678",
    "2023": "156",
    "2024": "3289",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Sonneratia alba",
    nama_lokal: "Pedada",
    "2020": "0",
    "2021": "455",
    "2022": "233",
    "2023": "828",
    "2024": "678",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Terminalia catappa",
    nama_lokal: "Ketapang",
    "2020": "0",
    "2021": "0",
    "2022": "432",
    "2023": "121",
    "2024": "56",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Vitex cofassus",
    nama_lokal: "Kupasa",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "289",
    "2024": "319",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Ipomoea pes-caprae",
    nama_lokal: "Batata Pantai",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "58",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Calophyllum inophyllum",
    nama_lokal: "Nyamplung",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "9",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Barringtonia asiatica",
    nama_lokal: "Keben",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "13",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
  {
    nama_latin: "Kandelia candel",
    nama_lokal: "Beras-beras",
    "2020": "0",
    "2021": "0",
    "2022": "0",
    "2023": "0",
    "2024": "271",
    iucn: "LC",
    cites: "NA",
    p: "Tidak dilindungi",
  },
];

const mambruk = [
  {
    nama_latin: "Goura cristata",
    nama_lokal: "Mambruk Ubiaat",
    "2020": "0",
    "2021": "0",
    "2022": "3",
    "2023": "10",
    "2024": "10",
    iucn: "VU",
    cites: "Apendiks II",
    p: "Dilindungi",
  },
];

const rusaTimor = [
  {
    nama_latin: "Rusa Timorensis",
    nama_lokal: "Rusa Timor",
    "2020": "14",
    "2021": "16",
    "2022": "19",
    "2023": "20",
    "2024": "21",
    iucn: "VU",
    cites: "Apendiks I",
    p: "Dilindungi",
  },
];

export const laporanTab = [
  {
    title: "Flora",
    value: "flora",
    contentTitle: "Daftar Flora Kilang RU VII Kasim",
    data: flora,
    is_konservasi: false,
  },
  {
    title: "Fauna",
    value: "fauna",
    contentTitle: "Daftar Fauna Kilang RU VII Kasim",
    data: fauna,
    is_konservasi: false,
  },
  {
    title: "Vegetasi Mangrove",
    value: "vegetasi_magrove",
    contentTitle: "Vegetasi Mangrove",
    data: mangrove,
    is_konservasi: false,
  },
  {
    title: "Mambruk",
    value: "mambruk",
    contentTitle: "Mambruk",
    data: mambruk,
    is_konservasi: true,
  },
  {
    title: "Rusa Timor",
    value: "rusa_timor",
    contentTitle: "Rusa Timor",
    data: rusaTimor,
    is_konservasi: true,
  },
];

export const posts = [
  {
    title:
      "Penangkaran Rusa Timor: Warisan Alam yang Dilestarikan di Kilang Pertamina",
    contents: [
      "Di tengah ancaman kepunahan, Rusa Timor menjadi salah satu satwa yang mendapatkan perhatian khusus dari PT Kilang Pertamina Internasional Refinery Unit VII Kasim. Melalui program penangkaran yang menjadi unggulan perusahaan, Rusa Timor kini dapat hidup dengan aman dan terlindungi. Program ini tidak hanya bertujuan untuk menjaga populasi satwa ini, tetapi juga untuk memastikan bahwa warisan alam ini dapat terus dinikmati oleh generasi mendatang.",
      "Program penangkaran yang dilakukan melibatkan berbagai upaya untuk menciptakan lingkungan yang ideal bagi pertumbuhan dan perkembangan Rusa Timor. Dengan pendekatan yang holistik, PT Kilang Pertamina berkomitmen untuk tidak hanya melestarikan satwa ini, tetapi juga mendukung upaya global dalam melindungi keanekaragaman hayati. Hasil absolut tahun 2024 menunjukkan keberhasilan program ini, menjadi bukti nyata dari dedikasi perusahaan dalam konservasi alam.",
      "Untuk memberikan gambaran yang lebih jelas mengenai keberhasilan program, diagram line chart berikut menampilkan data peningkatan populasi Rusa Timor di kawasan penangkaran sejak tahun 2019. Tren yang ditunjukkan dalam diagram ini memperlihatkan peningkatan populasi yang stabil, terutama setelah penerapan program pemeliharaan intensif pada tahun 2020.",
      "chart",
      "Peningkatan populasi ini mencerminkan efektivitas dari strategi yang diterapkan, termasuk perbaikan habitat dan pengawasan yang lebih ketat. Diagram ini juga menggarisbawahi bahwa upaya pelestarian ini berhasil membawa populasi Rusa Timor ke tingkat yang lebih aman, mengurangi risiko kepunahan di masa depan.",
      "Selain menjaga populasi Rusa Timor, program ini juga memberikan dampak positif pada ekosistem di sekitar area penangkaran. Keberadaan Rusa Timor membantu menjaga keseimbangan alam, seperti pengendalian vegetasi dan distribusi benih tanaman melalui mekanisme alami. Perusahaan juga telah bekerja sama dengan para ahli ekologi untuk terus memantau dan menyesuaikan strategi penangkaran, guna memastikan bahwa setiap langkah yang diambil selalu selaras dengan prinsip keberlanjutan.",
      "Pencapaian ini tidak hanya diakui di tingkat lokal, tetapi juga mendapat apresiasi dari berbagai lembaga konservasi di tingkat nasional dan internasional. PT Kilang Pertamina berharap bahwa program ini dapat menjadi model bagi upaya pelestarian satwa lainnya, serta berkontribusi pada keanekaragaman hayati di Indonesia.",
    ],
    thumbnail: "/bg-3.webp",
    author: "Admin",
    createdAt: "10 Agustus 2024",
    charts: [
      {
        title: "Populasi Rusa Timor",
        data: [
          { year: "2021", populasi: 16 },
          { year: "2022", populasi: 19 },
          { year: "2023", populasi: 20 },
          { year: "2024", populasi: 21 },
        ],
      },
    ],
    slug: "penangkaran-rusa-timor-warisan-alam-yang-dilestarikan-di-kilang-pertamina",
  },
  {
    title: "Penangkaran Mambruk Ubiaat: Upaya Melestarikan Satwa Endemik Papua",
    contents: [
      "Mambruk Ubiaat, burung langka yang hanya ditemukan di Papua, kini berada di bawah perlindungan PT Kilang Pertamina Internasional Refinery Unit VII Kasim. Program konservasi ini dirancang sebagai respons terhadap ancaman kepunahan yang dihadapi oleh burung endemik tersebut. Dengan penangkaran yang dilakukan secara intensif, perusahaan berhasil menjaga kelangsungan hidup Mambruk Ubiaat, memastikan bahwa satwa ini tetap menjadi bagian dari keanekaragaman hayati Indonesia.",
      "Melalui program unggulan ini, PT Kilang Pertamina tidak hanya fokus pada penangkaran, tetapi juga pada edukasi dan peningkatan kesadaran akan pentingnya pelestarian satwa. Hasil absolut terbaru dari program ini menunjukkan peningkatan populasi Mambruk Ubiaat, membuktikan efektivitas upaya yang telah dilakukan. Ini menjadi contoh nyata bagaimana aksi nyata dapat membawa perubahan positif bagi kelestarian alam.",
      "Untuk menggambarkan pencapaian program ini, diagram line chart di bawah ini menunjukkan peningkatan jumlah Mambruk Ubiaat yang berhasil ditangkar sejak tahun 2019. Dengan tren positif yang terus meningkat, diagram ini mencerminkan kesuksesan perusahaan dalam menjaga dan memperluas populasi satwa endemik ini.",
      "chart",
      "Keberhasilan ini tidak lepas dari kombinasi antara pendekatan ilmiah dan komitmen penuh perusahaan terhadap konservasi. Diagram ini mengilustrasikan bagaimana penanganan yang tepat, termasuk perbaikan habitat dan pengelolaan kesehatan satwa, telah berhasil meningkatkan populasi Mambruk Ubiaat secara signifikan.",
      "Perusahaan juga aktif berkolaborasi dengan komunitas lokal dan pemerintah daerah dalam program edukasi untuk meningkatkan kesadaran masyarakat tentang pentingnya pelestarian Mambruk Ubiaat. Keterlibatan masyarakat lokal dalam program ini telah membantu memperkuat dukungan terhadap upaya pelestarian, sehingga memastikan keberlangsungan jangka panjang.",
      "Dengan adanya peningkatan populasi yang konsisten, PT Kilang Pertamina Internasional Refinery Unit VII Kasim terus memperluas area konservasi dan meningkatkan fasilitas penangkaran. Langkah ini diambil untuk mengakomodasi kebutuhan Mambruk Ubiaat yang semakin meningkat, serta untuk menjaga keseimbangan ekosistem di sekitarnya.",
    ],
    thumbnail: "/bg-4.webp",
    author: "Admin",
    createdAt: "10 Agustus 2024",
    charts: [
      {
        title: "Populasi Mambruk",
        data: [
          { year: "2021", populasi: 0 },
          { year: "2022", populasi: 3 },
          { year: "2023", populasi: 10 },
          { year: "2024", populasi: 10 },
        ],
      },
    ],
    slug: "penangkaran-mambruk-ubiaat-upaya-melestarikan-satwa-endemik-papua",
  },
  {
    title:
      "Kawasan Konservasi Mangrove: Penjaga Ekosistem Pesisir di Kilang Pertamina",
    contents: [
      "Ekosistem mangrove di kawasan PT Kilang Pertamina Internasional Refinery Unit VII Kasim memainkan peran penting dalam menjaga keseimbangan ekosistem pesisir. Mangrove bukan hanya berfungsi sebagai pelindung pantai dari abrasi, tetapi juga sebagai habitat penting bagi banyak spesies. Program konservasi mangrove yang dijalankan oleh perusahaan ini menjadi salah satu upaya utama dalam menjaga keanekaragaman hayati dan melindungi lingkungan dari dampak perubahan iklim.",
      "Lebih dari sekadar konservasi, program ini juga menekankan pada potensi mangrove dalam penyerapan karbon, yang sangat penting dalam mengurangi emisi Gas Rumah Kaca (GRK). Hasil absolut tahun 2024 dari kawasan konservasi ini menunjukkan efektivitas program dalam meningkatkan penyerapan karbon, menjadikannya salah satu kontribusi nyata PT Kilang Pertamina dalam melindungi bumi dari pemanasan global.",
      "Untuk memberikan gambaran yang lebih jelas mengenai keberhasilan program konservasi mangrove, diagram line chart berikut menampilkan peningkatan luasan kawasan mangrove yang telah direhabilitasi sejak tahun 2019. Data ini menunjukkan keberhasilan program dalam memperluas kawasan konservasi dan meningkatkan fungsi ekosistem mangrove sebagai penyangga alami pesisir.",
      "chart",
      "Diagram ini menegaskan bahwa dengan langkah-langkah strategis yang diambil, perusahaan berhasil meningkatkan luasan kawasan mangrove secara signifikan. Tren peningkatan ini menunjukkan bahwa program yang dijalankan tidak hanya efektif dalam aspek rehabilitasi, tetapi juga dalam menjaga keberlanjutan ekosistem mangrove dalam jangka panjang.",
      "Selain itu, keberhasilan rehabilitasi mangrove juga berdampak pada peningkatan populasi spesies yang hidup di kawasan ini, termasuk berbagai jenis ikan, burung, dan hewan lainnya. Dengan melibatkan para ahli dan komunitas lokal, perusahaan terus berupaya untuk memastikan bahwa kawasan mangrove ini tetap terjaga dan dapat berfungsi optimal sebagai habitat bagi keanekaragaman hayati.",
      "Program ini juga menjadi bagian dari strategi perusahaan dalam menghadapi tantangan perubahan iklim. Dengan penyerapan karbon yang meningkat, kawasan mangrove ini berkontribusi signifikan dalam mengurangi emisi GRK, sekaligus melindungi pantai dari risiko abrasi dan bencana alam lainnya. Keberhasilan ini menjadikan PT Kilang Pertamina sebagai pionir dalam upaya konservasi mangrove di Indonesia.",
    ],
    thumbnail: "/bg-2.webp",
    author: "Admin",
    createdAt: "10 Agustus 2024",
    charts: [
      {
        title: "Konservasi Mangrove",
        data: [
          { year: "2021", populasi: 0 },
          { year: "2022", populasi: 3 },
          { year: "2023", populasi: 10 },
          { year: "2024", populasi: 10 },
        ],
      },
    ],
    slug: "kawasan-konservasi-mangrove-penjaga-ekosistem-pesisir-di-kilang-pertamina",
  },
  {
    title:
      "Serapan Karbondioksida dan Karbon: Kontribusi Kilang RU VII Kasim dalam Mengurangi Pemanasan Global",
    contents: [
      "PT Kilang Pertamina Internasional Refinery Unit VII Kasim memahami betul pentingnya peran tumbuhan sebagai carbon sink dalam upaya mengurangi emisi karbon di udara. Program serapan karbondioksida dan karbon yang dijalankan di kawasan ini menjadi salah satu langkah strategis dalam mendukung upaya global melawan pemanasan global. Setiap pohon yang ada di kawasan ini berperan penting dalam menyerap CO2, mengurangi potensi pelepasan karbon yang dapat mempercepat perubahan iklim.",
      "Hasil pemantauan terbaru menunjukkan bahwa program ini berhasil dalam meningkatkan serapan karbon di kawasan Kilang RU VII Kasim. Ini bukan hanya sekadar data, tetapi sebuah pencapaian yang mencerminkan komitmen perusahaan terhadap keberlanjutan lingkungan. Program ini menjadi salah satu kontribusi nyata PT Kilang Pertamina dalam menjaga bumi tetap hijau dan mengurangi dampak negatif dari Gas Rumah Kaca (GRK).",
      "Untuk menggambarkan pencapaian ini, diagram line chart berikut menunjukkan peningkatan jumlah karbon yang berhasil diserap di kawasan kilang sejak tahun 2019. Data ini menunjukkan tren peningkatan yang konsisten, mencerminkan efektivitas program serapan karbon yang diterapkan oleh perusahaan.",
      "chart",
      "Diagram ini menunjukkan bagaimana program yang konsisten dapat memberikan dampak yang signifikan terhadap penyerapan karbon di udara. Peningkatan serapan karbon ini merupakan bukti bahwa upaya yang dilakukan perusahaan dalam menjaga dan menambah vegetasi di kawasan kilang telah memberikan hasil yang positif.",
      "Selain itu, program ini juga melibatkan pemanfaatan teknologi hijau yang membantu meningkatkan efisiensi serapan karbon. Dengan metode ini, PT Kilang Pertamina tidak hanya bergantung pada proses alami, tetapi juga memaksimalkan potensi serapan melalui inovasi yang terus dikembangkan. Kolaborasi dengan institusi riset dan para ahli di bidang lingkungan turut memperkuat implementasi program ini.",
      "Sebagai bagian dari komitmen perusahaan untuk berkontribusi dalam mengurangi pemanasan global, PT Kilang Pertamina Internasional Refinery Unit VII Kasim berencana untuk terus mengembangkan program ini di masa mendatang. Dengan hasil yang sudah dicapai, perusahaan optimis bahwa upaya ini akan memberikan dampak positif yang lebih besar, tidak hanya bagi lingkungan sekitar, tetapi juga bagi upaya global dalam mengatasi perubahan iklim.",
    ],
    thumbnail: "/bg-2.webp",
    author: "Admin",
    createdAt: "10 Agustus 2024",
    charts: [
      {
        title: "Serapan Karbondioksida",
        data: [
          { year: "2021", populasi: 8.92 },
          { year: "2022", populasi: 8.97 },
          { year: "2023", populasi: 9.35 },
          { year: "2024", populasi: 9.66 },
        ],
      },
      {
        title: "Simpanan Karbon",
        data: [
          { year: "2021", populasi: 32.93 },
          { year: "2022", populasi: 39.42 },
          { year: "2023", populasi: 42.52 },
          { year: "2024", populasi: 45.34 },
        ],
      },
    ],
    slug: "serapan-karbondioksida-dan-karbon-kontribusi-kilang-ru-vii-kasim-dalam-mengurangi-pemanasan-global",
  },
  {
    title:
      "Indeks Keanekaragaman Hayati (H’): Komitmen Kilang Pertamina Terhadap Lingkungan",
    contents: [
      "PT Kilang Pertamina Internasional Refinery Unit VII Kasim terus menunjukkan komitmennya terhadap pelestarian lingkungan melalui pemantauan keanekaragaman hayati flora dan fauna di area operasionalnya. Indeks Keanekaragaman Hayati (H’) yang dihasilkan dari pemantauan rutin ini memberikan gambaran integral mengenai dampak operasional terhadap ekosistem di sekitarnya. Hal ini menunjukkan betapa pentingnya menjaga keseimbangan ekosistem demi keberlanjutan lingkungan.",
      "Dengan pendekatan yang komprehensif, perusahaan tidak hanya sekadar memantau, tetapi juga menerapkan langkah-langkah yang dapat meminimalkan dampak negatif dari aktivitas operasional terhadap keanekaragaman hayati. Pemantauan ini memberikan manfaat jangka panjang, memastikan bahwa flora dan fauna di sekitar area operasional tetap terjaga dengan baik, serta mencerminkan tanggung jawab perusahaan terhadap lingkungan.",
      "Untuk memberikan gambaran yang lebih jelas mengenai keberhasilan program, diagram line chart berikut menampilkan data peningkatan Indeks Keanekaragaman Hayati (H’) selama lima tahun terakhir. Diagram ini menunjukkan tren positif dari upaya konservasi yang telah dilakukan, dengan peningkatan signifikan yang terlihat sejak implementasi program restorasi ekosistem pada tahun 2020.",
      "chart",
      "Diagram ini mengilustrasikan bahwa sejak tahun 2020, setelah penerapan langkah-langkah khusus untuk restorasi dan perlindungan habitat, indeks keanekaragaman hayati terus mengalami peningkatan setiap tahunnya. Hal ini menunjukkan bahwa strategi yang diterapkan perusahaan tidak hanya efektif dalam meminimalkan dampak operasional, tetapi juga dalam memperbaiki kondisi ekosistem yang ada.",
      "Proses pemantauan keanekaragaman hayati di Kilang Pertamina melibatkan berbagai teknik ilmiah, mulai dari survei lapangan hingga analisis genetika. Dengan metode ini, perusahaan dapat mengidentifikasi perubahan dalam populasi flora dan fauna secara lebih mendetail. Data yang dikumpulkan kemudian dianalisis untuk mengetahui dampak dari setiap aktivitas operasional perusahaan terhadap ekosistem, yang menjadi dasar bagi pengambilan keputusan dalam manajemen lingkungan.",
      "Hasil dari pemantauan tersebut tidak hanya digunakan untuk kebutuhan internal perusahaan, tetapi juga dibagikan dengan para pemangku kepentingan, termasuk pemerintah dan lembaga konservasi. Transparansi ini menjadi salah satu bentuk akuntabilitas PT Kilang Pertamina dalam menjalankan tanggung jawab lingkungan. Dengan melibatkan berbagai pihak dalam evaluasi data, perusahaan memastikan bahwa tindakan yang diambil selalu berdasarkan prinsip kehati-hatian dan keberlanjutan.",
    ],
    thumbnail: "/bg-2.webp",
    author: "Admin",
    createdAt: "10 Agustus 2024",
    charts: [
      {
        title: "Indeks Keanekaragaman Hayati Flora RU VII Kasim",
        data: [
          { year: "2021", populasi: 3.02 },
          { year: "2022", populasi: 3.09 },
          { year: "2023", populasi: 3.11 },
          { year: "2024", populasi: 3.38 },
        ],
      },
      {
        title: "Indeks Keanekaragaman Hayati Fauna RU VII Kasim",
        data: [
          { year: "2021", populasi: 2.69 },
          { year: "2022", populasi: 2.89 },
          { year: "2023", populasi: 3.07 },
          { year: "2024", populasi: 3.11 },
        ],
      },
    ],
    slug: "indeks-keanekaragaman-hayati-h-komitmen-kilang-pertamina-terhadap-lingkungan",
  },
];
